FROM openjdk:13-jdk-alpine
LABEL maintainer=jon@jaggersoft.com

ARG VERSION=3.0.0

COPY install.sh .
RUN ./install.sh && rm -f ./install.sh

ENV GROOVY_HOME=/groovy-${VERSION}
ENV PATH=$GROOVY_HOME/bin:$PATH
