FROM amazoncorretto:26-alpine-jdk
LABEL maintainer=jon@jaggersoft.com

ARG VERSION=5.0.0

COPY install.sh .
RUN ./install.sh && rm -f ./install.sh

ENV GROOVY_HOME=/groovy-${VERSION}
ENV PATH=$GROOVY_HOME/bin:$PATH
